name: python_foundation
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0=pyhd8ed1ab_0
  - altair=5.0.1=py312hecd8cb5_0
  - anyio=4.2.0=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312h104f124_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - arrow-cpp=11.0.0=h694c41f_58_cpu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - aws-c-auth=0.7.11=h5ed86db_0
  - aws-c-cal=0.6.9=had988b7_2
  - aws-c-common=0.9.10=h10d778d_0
  - aws-c-compression=0.2.17=hb45f1eb_7
  - aws-c-event-stream=0.4.1=h451788f_1
  - aws-c-http=0.8.0=h1fa4523_1
  - aws-c-io=0.13.36=h3728bb0_3
  - aws-c-mqtt=0.10.0=hdd2773f_2
  - aws-c-s3=0.4.7=hf9a8137_3
  - aws-c-sdkutils=0.1.13=hb45f1eb_0
  - aws-checksums=0.1.17=hb45f1eb_6
  - aws-crt-cpp=0.26.0=h4285ddc_5
  - aws-sdk-cpp=1.11.210=hb301dda_9
  - azure-core-cpp=1.10.3=h926c267_0
  - azure-storage-blobs-cpp=12.10.0=he51d815_0
  - azure-storage-common-cpp=12.5.0=hf4badfb_2
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.6.2=py312hecd8cb5_0
  - blosc=1.21.5=heccf04b_0
  - boost-cpp=1.84.0=h07eb623_0
  - branca=0.7.0=pyhd8ed1ab_1
  - brotli=1.1.0=h0dc2134_1
  - brotli-bin=1.1.0=h0dc2134_1
  - brotli-python=1.1.0=py312heafc425_1
  - bzip2=1.0.8=h10d778d_5
  - c-ares=1.24.0=h10d778d_0
  - ca-certificates=2024.2.2=h8857fd0_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.18.0=h99e66fa_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py312h38bf5a0_0
  - cfitsio=4.3.1=h60fb419_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=py312hecd8cb5_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.2.0=py312hbf0bb39_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.0=py312heafc425_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=hf0c8a7f_1
  - fiona=1.9.5=py312h3aaa50d_2
  - folium=0.15.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h5bb23bf_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.47.0=py312h41838bb_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h60636b9_2
  - freexl=2.0.0=h3ec172f_0
  - gdal=3.8.2=py312h1d14960_0
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopandas=0.14.1=pyhd8ed1ab_0
  - geopandas-base=0.14.1=pyha770c72_0
  - geopy=2.4.1=pyhd8ed1ab_0
  - geos=3.12.1=h93d8f39_0
  - geotiff=1.7.1=h509af15_15
  - gettext=0.21.1=h8a4c099_0
  - gflags=2.2.2=h0a44026_0
  - giflib=5.2.1=hb7f2c08_3
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.37=py312hecd8cb5_0
  - glog=0.6.0=h8ac2a54_0
  - hdf4=4.2.15=h8138101_7
  - hdf5=1.14.3=nompi_h691f4bf_100
  - icu=73.2=hf5e326d_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=py312hecd8cb5_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - ipykernel=6.28.0=pyh3cd1d5f_0
  - ipython=8.19.0=pyh707e725_0
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - json-c=0.17=h8e11ae5_0
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpointer=2.4=py312hb401068_3
  - jsonschema-specifications=2023.11.2=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.20.0=pyhd8ed1ab_0
  - jupyter-lsp=2.2.1=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.6=pyh5bfe37b_1
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.6.0=py312hb401068_0
  - jupyter_events=0.9.0=pyhd8ed1ab_0
  - jupyter_server=2.12.1=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.1=pyhd8ed1ab_0
  - jupyterlab=4.0.9=pyhd8ed1ab_0
  - jupyterlab-git=0.50.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_0
  - jupyterlab_server=2.25.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.9=py312hecd8cb5_0
  - kealib=1.5.3=h5f07ac3_0
  - kiwisolver=1.4.5=py312h49ebfd2_1
  - krb5=1.21.2=hb884880_0
  - lcms2=2.16=ha2f27b4_0
  - lerc=4.0.0=hb486fe8_0
  - libabseil=20230802.1=cxx17_h048a20a_0
  - libaec=1.1.2=he965462_1
  - libarchive=3.7.2=hd35d340_1
  - libarrow=11.0.0=hdae7707_58_cpu
  - libblas=3.9.0=20_osx64_openblas
  - libboost=1.84.0=h5b2dd29_0
  - libboost-devel=1.84.0=h7728843_0
  - libboost-headers=1.84.0=h694c41f_0
  - libbrotlicommon=1.1.0=h0dc2134_1
  - libbrotlidec=1.1.0=h0dc2134_1
  - libbrotlienc=1.1.0=h0dc2134_1
  - libcblas=3.9.0=20_osx64_openblas
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.5.0=h726d00d_0
  - libcxx=16.0.6=hd57cbcb_0
  - libdeflate=1.19=ha4e1b8e_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=h04015c4_1
  - libexpat=2.5.0=hf0c8a7f_1
  - libffi=3.4.2=h0d85af4_5
  - libgdal=3.8.2=hf17bf98_0
  - libgfortran=5.0.0=13_2_0_h97931a8_1
  - libgfortran5=13.2.0=h2873a65_1
  - libglib=2.78.3=h198397b_0
  - libgoogle-cloud=2.12.0=hc0857f6_4
  - libgrpc=1.59.3=ha7f534c_0
  - libiconv=1.17=hd75f5a5_2
  - libjpeg-turbo=3.0.0=h0dc2134_1
  - libkml=1.3.0=hab3ca0e_1018
  - liblapack=3.9.0=20_osx64_openblas
  - libnetcdf=4.9.2=nompi_h7760872_113
  - libnghttp2=1.58.0=h64cf6d3_1
  - libopenblas=0.3.25=openmp_hfef2a42_0
  - libpng=1.6.39=ha978bb4_0
  - libpq=16.1=ha925e61_7
  - libprotobuf=4.24.4=h0ee05dc_0
  - libre2-11=2023.06.02=h4694dbf_0
  - librttopo=1.1.0=hf05f67e_15
  - libsodium=1.0.18=hbcb3906_1
  - libspatialindex=1.9.3=he49afe7_4
  - libspatialite=5.1.0=hebe6af1_4
  - libsqlite=3.44.2=h92b6c6a_0
  - libssh2=1.11.0=hd019ec5_0
  - libthrift=0.19.0=h064b379_1
  - libtiff=4.6.0=h684deea_2
  - libutf8proc=2.8.0=hb7f2c08_0
  - libwebp-base=1.3.2=h0dc2134_0
  - libxcb=1.15=hb7f2c08_0
  - libxml2=2.12.3=hc0ae0f7_0
  - libzip=1.10.1=hc158999_3
  - libzlib=1.2.13=h8a1eda9_5
  - llvm-openmp=17.0.6=hb6ac08f_0
  - lz4-c=1.9.4=hf0c8a7f_0
  - lzo=2.10=haf1e3a3_1000
  - mapclassify=2.6.1=pyhd8ed1ab_0
  - markdown-it-py=2.2.0=py312hecd8cb5_1
  - markupsafe=2.1.3=py312h104f124_1
  - matplotlib=3.8.2=py312hb401068_0
  - matplotlib-base=3.8.2=py312h302682c_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=py312hecd8cb5_0
  - minizip=4.0.3=h23f18a7_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.13.1=pyhd8ed1ab_0
  - nbdime=4.0.1=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=h93d8f39_2
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - notebook=7.0.6=pyhd8ed1ab_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - nspr=4.35=hea0b92c_0
  - nss=3.96=ha05da47_0
  - numpy=1.26.2=py312hfd3bce2_0
  - openjpeg=2.5.0=ha4da562_3
  - openssl=3.2.1=hd75f5a5_0
  - orc=1.9.2=h9ab30d4_0
  - overrides=7.4.0=pyhd8ed1ab_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.4=py312haf8ecfc_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.42=h0ad2156_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.1.0=py312h0c70c2f_0
  - pip=23.3.2=pyhd8ed1ab_0
  - pixman=0.42.2=he965462_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - poppler=23.12.0=hdd5a5e8_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.1=hbd19fd8_7
  - proj=9.3.1=h81faed2_0
  - prometheus_client=0.19.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - protobuf=4.24.4=py312h317d3df_0
  - psutil=5.9.7=py312h41838bb_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=11.0.0=py312h0b9b6c3_2
  - pycparser=2.21=pyhd8ed1ab_0
  - pydeck=0.8.0=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyobjc-core=10.1=py312h74abf1d_0
  - pyobjc-framework-cocoa=10.1=py312h74abf1d_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyproj=3.6.1=py312h14d93e9_5
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.0=h30d4d87_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h104f124_1
  - pyzmq=25.1.2=py312hc789acb_0
  - rasterio=1.3.9=py312h2bf6802_2
  - re2=2023.06.02=hd34609a_0
  - readline=8.2=h9e318b2_1
  - referencing=0.32.0=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.3.5=py312hecd8cb5_1
  - rpds-py=0.15.2=py312h6e28e45_0
  - rtree=1.1.0=py312h8974cf7_0
  - scikit-learn=1.3.2=py312h5e37b4f_2
  - scipy=1.11.4=py312heccc6a5_0
  - send2trash=1.8.2=pyhd1c38e8_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - shapely=2.0.2=py312h8fb43f9_1
  - six=1.16.0=pyh6c4a22f_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.1.10=h225ccf5_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.44.2=h7461747_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - streamlit=1.29.0=pyhd8ed1ab_0
  - tenacity=8.2.2=py312hecd8cb5_1
  - terminado=0.18.0=pyh31c8845_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tiledb=2.18.3=h4df5763_1
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=h1abcd95_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=py312hecd8cb5_0
  - tornado=6.3.3=py312h104f124_1
  - traitlets=5.14.0=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing-extensions=4.9.0=hd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzcode=2023c=hb7f2c08_0
  - tzdata=2023c=h71feb2d_0
  - tzlocal=2.1=py312hecd8cb5_1
  - uri-template=1.3.0=pyhd8ed1ab_0
  - uriparser=0.9.7=hf0c8a7f_1
  - validators=0.18.2=pyhd3eb1b0_0
  - watchdog=2.1.6=py312h3333b6a_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - widgetsnbextension=3.5.1=pyh9f0ad1d_3
  - xerces-c=3.2.5=hbbe9ea5_0
  - xorg-libxau=1.0.11=h0dc2134_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xyzservices=2023.10.1=pyhd8ed1ab_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.5=h93d8f39_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8a1eda9_5
  - zstd=1.5.5=h829000d_0
  - pip:
      - ai-einblick-prompt==0.1.12
      - boto3==1.34.62
      - botocore==1.34.62
      - cachecontrol==0.14.0
      - click==8.0.4
      - cognite-jupyterlab-copilot==3.5.11
      - geojson==2.5.0
      - iso3166==2.1.1
      - jmespath==1.0.1
      - jsonschema==3.2.0
      - jsonseq==1.0.0
      - mapbox==0.18.1
      - mapbox-tilesets==1.9.3
      - mercantile==1.1.6
      - msgpack==1.0.8
      - polyline==2.0.2
      - pyrsistent==0.20.0
      - requests-toolbelt==1.0.0
      - s3transfer==0.10.0
      - supermercado==0.2.0
      - uritemplate==4.1.1
      - urllib3==2.0.7
prefix: /Users/humanperson/anaconda3/envs/python_foundation
